# Generated by Django 4.2.24 on 2025-11-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coin',
            field=models.IntegerField(default='0', verbose_name='Монеты'),
        ),
    ]
